version: "3"
services:
  web:
    image: "dbist/flask-standalone:v3"
    deploy:
# fix python code to only execute schema creation once, otherwise app doesn't work
# then you can scale the app to add more replicas
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    ports:
      - "5000:5000"
# figure out how to bind volume on remote machine, otherwise getting error
#    volumes:
#      - .:/code
    environment:
      FLASK_ENV: development
    depends_on:
      - pqs
    networks:
      - webnet
  pqs:
    image: "dbist/apache-phoenix-pqs:4.14.2"
    ports:
      - "8765:8765"
# figure out where to create this directory? otherwise it doesn't work
#    volumes:
#      - "/home/docker/data:/pqs"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: ["/usr/local/bin/pqs-entrypoint.sh", "-bash"]
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

networks:
  webnet:
