version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  pqs:
    image: "dbist/apache-phoenix-pqs:4.14.3"
