version: '3'
services:
  web:
    image: dbist/flask-standalone:stable
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    networks:
      - webnet
  pqs:
    image: "dbist/apache-phoenix-pqs:4.14.2"
networks:
  webnet:
